-- ============================================================
-- Backfill 2026 weekly clinic data from the master KPI spreadsheet
-- (CLINIC - ADJUST + HYDRO / GYM MEMBERSHIPS / CLINIC - PODIATRY tabs).
-- Covers week ending 2026-01-03 through 2026-07-11 (28 weeks).
-- Only fills columns that are still empty (coalesce) so it never
-- overwrites anything you've already entered through the app.
-- ============================================================
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-01-03', 19581.38, 167, 0.7867, 0.8718, 0.6579, 0.4904, 15, 1917.01, 84.49, 232.0, 1855.8, 23)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-01-10', 50117.58, 433, 0.8561, 0.8679, 0.8388, 0.6528, 20, 2247.69, 88.81, 400.0, null, 63)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-01-17', 50977.2, 433, 0.8353, 0.8455, 0.7338, 0.7917, 34, 1825.88, 72.12, 310.4, 2417.82, 72)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-01-24', 52448.38, 445, 0.8905, 0.9092, 0.7684, 0.875, 27, 2201.12, 86.88, 433.6, 2417.82, 70)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-01-31', 39215.18, 331, 0.8473, 0.8501, 0.8958, 0.7708, 29, 2239.47, 88.53, 264.2, 2024.32, 50)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-02-07', 51791.62, 445, 0.785, 0.7938, 0.6984, 0.8611, 32, 2288.42, 93.08, 422.8, 2024.32, 64)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-02-14', 49805.19, 423, 0.7945, 0.8127, 0.7196, 0.7431, 28, 2597.29, 102.71, 412.0, 2489.53, 75)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-02-21', 52452.3, 457, 0.8115, 0.8078, 0.7895, 0.8958, 31, 2472.21, 97.79, 623.6, 2489.53, 51)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-02-28', 45557.02, 387, 0.7896, 0.793, 0.6987, 0.9375, 23, 2684.02, 105.98, 613.16, 2173.04, 65)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-03-07', 50579.04, 436, 0.8253, 0.8464, 0.7472, 0.7708, 31, 2744.1, 110.9, 454.2, 2173.04, 62)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-03-14', 47112.73, 412, 0.8159, 0.8327, 0.7403, 0.7986, 19, 2789.75, 110.25, 428.56, 1973.7, 52)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-03-21', 51597.2, 450, 0.8497, 0.8486, 0.8741, 0.8125, 22, 2722.37, 107.63, 537.6, 1973.7, 64)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-03-28', 43017.72, 389, 0.7757, 0.7816, 0.8037, 0.6667, 26, 2853.74, 112.76, 507.6, 2526.42, 70)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-04-04', 39755.64, 363, 0.8927, 0.9075, 0.838, 0.8696, 15, 2432.89, 96.11, 596.93, 2526.42, 62)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-04-11', 35477.3, 311, 0.9264, 0.9323, 0.9306, 0.875, 18, 2734.46, 108.04, 719.0, 2661.92, 62)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-04-18', 48283.96, 424, 0.8838, 0.8777, 0.9232, 0.8542, 29, 2681.6, 105.9, 599.0, 2661.92, 65)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-04-25', 46930.47, 422, 0.8052, 0.8161, 0.7611, 0.7847, 22, 2671.92, 105.58, 888.66, 2222.31, 72)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-05-02', 48871.62, 442, 0.8308, 0.8219, 0.8877, 0.8056, 21, 2546.84, 100.66, 638.2, 2222.31, 58)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-05-09', 39253.0, 349, 0.8624, 0.8715, 0.8391, 0.8264, 17, 2671.92, 105.58, 671.6, 2222.31, 48)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-05-16', 48523.85, 439, 0.854, 0.8543, 0.8423, 0.875, 24, 2703.49, 109.01, 622.16, 2222.31, 72)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-05-23', 51423.53, 457, 0.8171, 0.8162, 0.7543, 0.9514, 43, 3071.35, 121.15, 775.76, 2658.26, 67)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-05-30', 51349.92, 452, 0.8158, 0.8128, 0.8322, 0.8125, 39, 2946.27, 116.23, 748.88, 2658.26, 66)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-06-06', 48539.74, 435, 0.8089, 0.8124, 0.7755, 0.8403, 29, 2946.27, 116.23, 649.52, 2348.55, 71)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-06-13', 48663.58, 432, 0.829, 0.8229, 0.8595, null, 25, 2948.65, 118.85, 976.6, 2348.55, 69)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-06-20', 45354.24, 406, 0.8184, 0.831, 0.755, null, 29, 2937.5, 111.47, 728.4, 2148.7, 46)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-06-27', 48509.43, 434, 0.8491, 0.8427, 0.8809, null, 27, 2614.0, 99.22, 969.4, 2148.7, 65)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-07-04', 44882.54, 406, 0.8018, 0.8047, 0.8592, 0.7153, 27, 2742.5, 104.09, 741.12, 2262.17, 68)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
insert into weekly_kpis (week_ending, total_rev, total_consults, clinic_occ, physio_occ, massage_occ, ep_occ, total_nc, m_glofox, m_glofox_fees, m_gym3p, m_pod_rev, m_pod_c) values ('2026-07-11', 47694.12, 397, 0.8851, 0.8812, 0.9437, 0.8611, 21, 2612.5, 99.17, 823.8, 2262.17, 68)
  on conflict (week_ending) do update set total_rev = coalesce(weekly_kpis.total_rev, excluded.total_rev), total_consults = coalesce(weekly_kpis.total_consults, excluded.total_consults), clinic_occ = coalesce(weekly_kpis.clinic_occ, excluded.clinic_occ), physio_occ = coalesce(weekly_kpis.physio_occ, excluded.physio_occ), massage_occ = coalesce(weekly_kpis.massage_occ, excluded.massage_occ), ep_occ = coalesce(weekly_kpis.ep_occ, excluded.ep_occ), total_nc = coalesce(weekly_kpis.total_nc, excluded.total_nc), m_glofox = coalesce(weekly_kpis.m_glofox, excluded.m_glofox), m_glofox_fees = coalesce(weekly_kpis.m_glofox_fees, excluded.m_glofox_fees), m_gym3p = coalesce(weekly_kpis.m_gym3p, excluded.m_gym3p), m_pod_rev = coalesce(weekly_kpis.m_pod_rev, excluded.m_pod_rev), m_pod_c = coalesce(weekly_kpis.m_pod_c, excluded.m_pod_c);
